trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VAR_subscription_id: $(subscription_id)
  TF_VAR_tenant_id: $(tenant_id)
  TF_VAR_client_id: $(client_id)
  TF_VAR_client_secret: $(client_secret)
  TF_VAR_acr_username: $(acr_username)
  TF_VAR_acr_password: $(acr_password)
  TF_VAR_acr_email: $(acr_email)

steps:


- script: |
    terraform init
    terraform apply -auto-approve
  displayName: 'Run Terraform Apply'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)
