apiVersion: batch/v1
kind: CronJob
metadata:
  name: vehicleusage-simulator
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: vehicleusage-simulator
              image: railsightregistry.azurecr.io/railsimulator:latest
              command: ["python", "data_simulator/simulate_vehicle_usage.py"]
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: acr-secret
